//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DupesMaintWinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckSum
    {
        public int Id { get; set; }
        public string SHA { get; set; }
        public string Folder { get; set; }
        public string TheFileName { get; set; }
        public string FileExt { get; set; }
        public int FileSize { get; set; }
        public System.DateTime FileCreateDt { get; set; }
        public int TimerMs { get; set; }
        public string Notes { get; set; }
    }
}
