//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLog.File
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckSumDup
    {
        public int Id { get; set; }
        public string SHA { get; set; }
        public string ToDelete { get; set; }
    }
}
